In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('./training.csv', index_col='Unnamed: 0')

In [13]:
df

,TEAM_ID_HOME,TEAM_NAME_HOME,WL_HOME,MIN_HOME,PTS_HOME,FGM_HOME,FGA_HOME,FG_PCT_HOME,FG3M_HOME,FG3A_HOME,...,FT_PCT_AWAY,OREB_AWAY,DREB_AWAY,REB_AWAY,AST_AWAY,STL_AWAY,BLK_AWAY,TOV_AWAY,PF_AWAY,PLUS_MINUS_AWAY
6009,1610612737,Atlanta Hawks,L,240,122,44,96,0.458,17,44,...,0.793,14,35,49,29,9,8,16,19,7.0
6010,1610612737,Atlanta Hawks,L,240,109,38,87,0.437,18,46,...,0.920,7,32,39,23,10,4,15,14,8.0
6011,1610612737,Atlanta Hawks,W,238,127,48,86,0.558,14,30,...,0.600,10,28,38,24,5,5,10,17,-14.0
6012,1610612737,Atlanta Hawks,L,240,113,42,94,0.447,12,35,...,0.708,12,33,45,24,7,6,12,19,1.0
6013,1610612737,Atlanta Hawks,W,264,147,51,116,0.440,18,49,...,0.833,22,37,59,28,8,6,16,24,-2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12316,1610612752,New York Knicks,W,242,126,46,100,0.460,19,42,...,0.615,11,35,46,31,2,7,13,22,-21.0
12317,1610612754,Indiana Pacers,W,240,152,55,95,0.579,20,38,...,0.767,12,24,36,26,7,5,11,15,-41.0
12318,1610612756,Phoenix Suns,L,241,121,43,80,0.538,16,32,...,0.923,9,32,41,37,7,5,8,21,11.0
12319,1610612756,Phoenix Suns,L,239,114,42,83,0.506,18,39,...,0.750,8,29,37,25,10,9,12,17,1.0
12320,1610612760,Oklahoma City Thunder,W,241,123,46,89,0.517,15,39,...,0.667,13,30,43,24,7,6,24,13,-36.0

In [14]:
df['SEASON'] = df['SEASON_ID'].apply(lambda x: str(x)[1:])

In [15]:
import json

In [16]:
with open('../api/app/ga/data/team_mapping_id.json') as f:
    mapping = json.load(f)

In [17]:
df['TEAM_HOME'] = df['TEAM_NAME_HOME'].apply(lambda x: x.split()[-1])
df['TEAM_AWAY'] = df['TEAM_NAME_AWAY'].apply(lambda x: x.split()[-1])
df['TEAM_HOME'] = df['TEAM_HOME'].map(mapping)
df['TEAM_AWAY'] = df['TEAM_AWAY'].map(mapping)

In [18]:
df['TARGET'] = df['WL_HOME'].apply(lambda x: int(x == 'W'))

In [19]:
df = df[df['GAME_DATE'] >= '2023-12-01']

In [20]:
df[["GAME_DATE", "SEASON", "TEAM_HOME", "TEAM_AWAY", "TARGET"]].to_csv('training_data_2024.csv', index=False)